truncate table COMMENTS CASCADE;
truncate table BOOKINGS CASCADE;
truncate table ITEMS CASCADE;
truncate table REQUESTS CASCADE;
truncate table USERS CASCADE;

ALTER SEQUENCE pk_comments RESTART WITH 1;
ALTER SEQUENCE pk_bookings RESTART WITH 1;
ALTER SEQUENCE pk_items RESTART WITH 1;
ALTER SEQUENCE pk_requests RESTART WITH 1;
ALTER SEQUENCE pk_user RESTART WITH 1;